version: "3"

services:
    #servidor de base de datos oficial de mysql
    #para acceder a la base de datos poner el siguiente comando: mysql -P 3306 --protocol=tcp -u root -p
    mysql:
        image: mysql:5.7 #esta versión posee una vulnerabilidad de explotación remota link: cso.computerworld.es/alertas/una-vulnerabilidad-en-mysql-permite-la-explotacion-remota-de-sus-servidores
        container_name: mysql
        environment: 
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=R0b0t1cs!
            #con este user vamos a hacer los robots y con el usuario root van a estar los usuarios admin (no se yo si esto va a ser asi)
            # - MYSQL_USER=main_user
            # - MYSQL_PASSWORD=Pr0duct10nD@t@b@s3
        networks:
            - my-network
        
        volumes:
            #volumen montado para que los datos sean persistentes
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./volumenes/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - my-network

    phpmyadmin:
        container_name: php_myadmin
        image: phpmyadmin/phpmyadmin
        networks:
            - my-network
        ports: 
            - 8080:80
        environment:
            - PMA_HOST=mysql 
            - MYSQL_ROOT_PASSWORD=R0b0t1cs!
        depends_on: 
            - mysql

    web:
        container_name: docker_php
        build:
            context: ./dockerfiles
            dockerfile: apache-php.dockerfile
        ports:
            - "80:80"
        volumes:
            - ./html:/var/www/html
        networks:
            - my-network

    #ubuntu:
    #    container_name: ubuntu
    #    build:
    #        context: ./dockerfiles:/ 
    #testingcommingithub
    #test

networks:
    my-network: