version: "3"

services:
    
    mysql:
        image: mysql:5.7 
        container_name: mysql
        environment: 
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=password

        networks:
            - my-network
        
        volumes:
            #volumen montado para que los datos sean persistentes
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./volumenes/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - my-network
        #f25a2fc72690b780b2a14e140ef6a9e0 = iloveyou - pepe
        #5f4dcc3b5aa765d61d8327deb882cf99 = password - admin 
        # how to - john --format=raw-md5 --wordlist /usr/share/wordlists/rockyou.txt hash.txt

    phpmyadmin:
        container_name: php_myadmin
        image: phpmyadmin/phpmyadmin
        networks:
            - my-network
        ports: 
            - 8080:80
        environment:
            - PMA_HOST=mysql 
            - MYSQL_ROOT_PASSWORD=password
        depends_on: 
            - mysql

    web:
        container_name: docker_php
        build:
            context: ./dockerfiles
            dockerfile: apache-php.dockerfile
        ports:
            - "80:80"
        volumes:
            - ./html:/var/www/html
        networks:
            - my-network

    openssh-server:
        container_name: ubuntussh
        build:
            context: ./dockerfiles
            dockerfile: ubuntu.dockerfile
        ports:
            - "22:22"
        volumes:
            - ./volumenes/ubuntu:/home/
        networks:
            - my-network
    

networks:
    my-network:

#test